/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hwen' at '7/13/16 3:32 PM' with Gradle 2.14
 *
 * @author hwen, @date 7/13/16 3:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
